language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"

before_install:
  - npm update -g npm

after_success:
  - ./node_modules/.bin/jscoverage lib lib-cov
  - ./node_modules/.bin/mocha -R mocha-lcov-reporter ./node_modules/coveralls/bin/coveralls.js
